function(assign_source_group)
    foreach(SOURCE IN ITEMS ${ARGN})
    get_filename_component(SOURCE_PATH "${SOURCE}" PATH)
    file(RELATIVE_PATH SOURCE_PATH_REL "${SRC_ROOT_PATH}" "${SOURCE_PATH}")
    string(REPLACE "/" "\\" GROUP_PATH "${SOURCE_PATH_REL}")
    source_group("${GROUP_PATH}" FILES "${SOURCE}")
endforeach()
endfunction(assign_source_group)

if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    message("debug mode")
elseif (CMAKE_BUILD_TYPE EQUAL "Release")
    message("release mode")
endif (CMAKE_BUILD_TYPE STREQUAL "Debug")